language: go
go:
- 1.x
script:
- go get
- go build
sudo: false
before_deploy:
- echo "Deploying $TRAVIS_TAG to GitHub releases"
- tar czf consul-bench.tar.gz consul-bench
deploy:
  provider: releases
  api_key:
    secure: IqBSyfPDigsnT46m28FDUEnbwScaglg+gJTzRnaHmQ3NNhNxSkEDuzzc+SxTKvJGPIMKopknkdi3di/Is7p8khdqqz/l81DBF2e+ZnYGmQWiqsko61II360vXf4o5meycY7xeijxbXyRgr1yc8e7Pq7ePTPpDIK39cogTDhLOkoYOZtczUoQ5Tx8WfQgGfpx8idbo00iVB0SvqxaPTlX1ET+9zlzuRLciVP3OI1cCB0upNtp67QRzRgWtsCwaJsLsnQDJVMpzgXSI3ppAWjoltnT4Kc4WTOxucn0wqNfDnaBgqoMCIgJ49eogsZnqnRXC90YV2tLjMWZ8TZ3HiNpm4uQEGYJ9cl1/JiPwUaK9cRLQ/dTdi7bHRip+0RZGEMDIclrQxhpX/rfsbWGgTMzLqGPaGfM3cipPR5e9JkFqNul7Q0UnRWtDc3rOv2XaBJn9XIAOkCSJYe7d8S64725P9aBD26pT7GPK+X2yf+tdOocX1tc0gq9C+QxsMWvbAphquroq/VZEssTML79GSqxON+LuocYrXp3YhFNAGztXHRGLWBWBWUgzzro9ee9qFHZY46YWwdD98IBcGPSGBYleW57F8EAfcwE/5HWDyOgF3I2kApQkPIQjqZUiF9Dj3UJGul3fe4gn+iHBP7PbIS67xG+EOCep5O5vLihZ34EJ+0=
  file: consul-bench.tar.gz
  skip_cleanup: true
  on:
    repo: criteo/consul-bench
    tags: true
